#!/bin/bash
clear
echo "=========================================="
echo "WHAT DO I SEE RIGHT NOW?"
echo "=========================================="
echo ""
echo "A. If you see 'WizDevTech | Technology Execution Partners'"
echo "   with a professional looking site → GOOD, full site deployed"
echo ""
echo "B. If you see 'Updated' with just a timestamp → BAD, simplified version"
echo ""
echo "C. If you see 'WizDevTech - Complete Site Loading...' → In between"
echo ""
echo "=========================================="
echo "QUICK TEST:"
curl -s "https://wizdevtechlanding26-production.info-wizdevtech.workers.dev/" | grep -o "<title>[^<]*</title>"
echo "=========================================="
echo "Open this URL in your browser:"
echo "https://wizdevtechlanding26-production.info-wizdevtech.workers.dev/"
echo "=========================================="
